steps:

#Build docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 
          'us-central1-docker.pkg.dev/off-net-dev/math-app-repo/math-app-image:v1',
          '.' 
        ]

#Push image to Artifact Registry
images:
- 'us-central1-docker.pkg.dev/off-net-dev/math-app-repo/math-app-image:v1'

#Release to GKE
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [ 'deploy', releases', 
        'create', 'math-app-release-004',
        'delivery-pipeline=math-app-pipeline',
        'region=us-central1',
        '--images=math-app=us-central1-docker.pkg.dev/off-net-dev/math-app-repo/math-app-image:v1'
      ]