steps:

#Build docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', 
          '-t', 
          'us-central1-docker.pkg.dev/off-net-dev/math-app-repo/math-app-image:$SHORT_SHA',
          '.' 
        ]
images:
- 'us-central1-docker.pkg.dev/off-net-dev/math-app-repo/math-app-image:tag1'