apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: math-app-1
description: main application pipeline
serialPipeline:
 stages:
 - targetId: dev
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsdev
description: development cluster
gke:
 cluster: projects/off-net-dev/locations/us-west2/clusters/math-app-cluster-dev
